export enum CropType {
  UNKNOWN_CROPTYPE = 0,
  CORN = 1,
  COTTON = 2,
  RICE = 3,
  SORGHUM = 4,
  SOYBEANS = 5,
  SUNFLOWER = 6,
  PEANUTS = 7,
  TOBACCO = 8,
  SWEET_CORN = 9,
  POP_OR_ORN_CORN = 10,
  MINT = 11,
  BARLEY = 12,
  DURUM_WHEAT = 13,
  SPRING_WHEAT = 14,
  WINTER_WHEAT = 15,
  OTHER_SMALL_GRAINS = 16,
  DBL_CROP_WINWHT_SOYBEANS = 17,
  RYE = 18,
  OATS = 19,
  MILLET = 20,
  SPELTZ = 21,
  CANOLA = 22,
  FLAXSEED = 23,
  SAFFLOWER = 24,
  RAPE_SEED = 25,
  MUSTARD = 26,
  ALFALFA = 27,
  OTHER_HAY_NON_ALFALFA = 28,
  CAMELINA = 29,
  BUCKWHEAT = 30,
  SUGARBEETS = 31,
  DRY_BEANS = 32,
  POTATOES = 33,
  OTHER_CROPS = 34,
  SUGARCANE = 35,
  SWEET_POTATOES = 36,
  MISC_VEGS_FRUITS = 37,
  WATERMELONS = 38,
  ONIONS = 39,
  CUCUMBERS = 40,
  CHICK_PEAS = 41,
  LENTILS = 42,
  PEAS = 43,
  TOMATOES = 44,
  CANEBERRIES = 45,
  HOPS = 46,
  HERBS = 47,
  CLOVER_WILDFLOWERS = 48,
  SOD_GRASS_SEED = 49,
  SWITCHGRASS = 50,
  FALLOW_IDLE_CROPLAND = 51,
  FOREST = 52,
  SHRUBLAND = 53,
  BARREN = 54,
  CHERRIES = 55,
  PEACHES = 56,
  APPLES = 57,
  GRAPES = 58,
  CHRISTMAS_TREES = 59,
  OTHER_TREE_CROPS = 60,
  CITRUS = 61,
  PECANS = 62,
  ALMONDS = 63,
  WALNUTS = 64,
  PEARS = 65,
  CLOUDS_NO_DATA = 66,
  DEVELOPED = 67,
  WATER = 68,
  WETLANDS = 69,
  NONAG_UNDEFINED = 70,
  AQUACULTURE = 71,
  OPEN_WATER = 72,
  PERENNIAL_ICE_SNOW = 73,
  DEVELOPED_OPEN_SPACE = 74,
  DEVELOPED_LOW_INTENSITY = 75,
  DEVELOPED_MED_INTENSITY = 76,
  DEVELOPED_HIGH_INTENSITY = 77,
  DECIDUOUS_FOREST = 79,
  EVERGREEN_FOREST = 80,
  MIXED_FOREST = 81,
  GRASSLAND_PASTURE = 83,
  WOODY_WETLANDS = 84,
  HERBACEOUS_WETLANDS = 85,
  PISTACHIOS = 86,
  TRITICALE = 87,
  CARROTS = 88,
  ASPARAGUS = 89,
  GARLIC = 90,
  CANTALOUPES = 91,
  PRUNES = 92,
  OLIVES = 93,
  ORANGES = 94,
  HONEYDEW_MELONS = 95,
  BROCCOLI = 96,
  PEPPERS = 97,
  POMEGRANATES = 98,
  NECTARINES = 99,
  GREENS = 100,
  PLUMS = 101,
  STRAWBERRIES = 102,
  SQUASH = 103,
  APRICOTS = 104,
  VETCH = 105,
  DBL_CROP_WINWHT_CORN = 106,
  DBL_CROP_OATS_CORN = 107,
  LETTUCE = 108,
  PUMPKINS = 109,
  DBL_CROP_LETTUCE_DURUM_WHT = 110,
  DBL_CROP_LETTUCE_CANTALOUPE = 111,
  DBL_CROP_LETTUCE_COTTON = 112,
  DBL_CROP_LETTUCE_BARLEY = 113,
  DBL_CROP_DURUM_WHT_SORGHUM = 114,
  DBL_CROP_BARLEY_SORGHUM = 115,
  DBL_CROP_WINWHT_SORGHUM = 116,
  DBL_CROP_BARLEY_CORN = 117,
  DBL_CROP_WINWHT_COTTON = 118,
  DBL_CROP_SOYBEANS_COTTON = 119,
  DBL_CROP_SOYBEANS_OATS = 120,
  DBL_CROP_CORN_SOYBEANS = 121,
  BLUEBERRIES = 122,
  CABBAGE = 123,
  CAULIFLOWER = 124,
  CELERY = 125,
  RADISHES = 126,
  TURNIPS = 127,
  EGGPLANTS = 128,
  GOURDS = 129,
  CRANBERRIES = 130,
  DBL_CROP_BARLEY_SOYBEANS = 134,
  LATE_CORN = 201,
  LATE_SOYBEAN = 202,
  FLOODING = 203,
  COVER_CROP = 204,
  NONE = 205,
  MEADOW_FESCUE = 206,
  WHEAT = 207,
  FABA_BEANS = 208,
  CLOVER = 209,
  RASPBERRY = 210,
  RED_SWISS_CHARD = 211,
  GREEN_SWISS_CHARD = 212,
  RED_BEET = 213,
  CEREALS = 214,
  OTHER_GRAINS = 215,
  QUINOA_AND_SORGHUM = 216,
  CANOLA_AND_RAPESEED = 217,
  WET_CORN = 218,
  HARD_RED_WINTER_WHEAT = 219,
  HARD_RED_SPRING_WHEAT = 221,
  EURO_RYE = 220
}

export const crop = [
  { type: 'Corn', color: '#ffd300', value: CropType.CORN },
  { type: 'Wet Corn', color: '#ffd300', value: CropType.WET_CORN },
  { type: 'Cotton', color: '#ff2626', value: CropType.COTTON },
  { type: 'Rice', color: '#00a8e2', value: CropType.RICE },
  { type: 'Sorghum', color: '#ff9e0a', value: CropType.SORGHUM },
  { type: 'Soybeans', color: '#267000', value: CropType.SOYBEANS },
  { type: 'Sunflower', color: '#ffff00', value: CropType.SUNFLOWER },
  { type: 'Peanuts', color: '#70a500', value: CropType.PEANUTS },
  { type: 'Tobacco', color: '#00af49', value: CropType.TOBACCO },
  { type: 'Sweet Corn', color: '#dda50a', value: CropType.SWEET_CORN },
  { type: 'Pop or Orn Corn', color: '#dda50a', value: CropType.POP_OR_ORN_CORN },
  { type: 'Mint', color: '#7cd3ff', value: CropType.MINT },
  { type: 'Barley', color: '#e2007c', value: CropType.BARLEY },
  { type: 'Wheat', color: '#bf870d', value: CropType.WHEAT },
  { type: 'Durum Wheat', color: '#896054', value: CropType.DURUM_WHEAT },
  { type: 'Spring Wheat', color: '#d8b56b', value: CropType.SPRING_WHEAT },
  { type: 'Winter Wheat', color: '#a57000', value: CropType.WINTER_WHEAT },
  { type: 'Other Small Grains', color: '#d69ebc', value: CropType.OTHER_SMALL_GRAINS },
  { type: 'Dbl Crop WinWht/Soybeans', color: '#707000', value: CropType.DBL_CROP_WINWHT_SOYBEANS },
  { type: 'Rye', color: '#aa007c', value: CropType.RYE },
  { type: 'Oats', color: '#a05989', value: CropType.OATS },
  { type: 'Millet', color: '#700049', value: CropType.MILLET },
  { type: 'Speltz', color: '#d69ebc', value: CropType.SPELTZ },
  { type: 'Canola', color: '#d1ff00', value: CropType.CANOLA },
  { type: 'Flaxseed', color: '#7c99ff', value: CropType.FLAXSEED },
  { type: 'Safflower', color: '#d6d600', value: CropType.SAFFLOWER },
  { type: 'Rape Seed', color: '#d1ff00', value: CropType.RAPE_SEED },
  { type: 'Mustard', color: '#00af49', value: CropType.MUSTARD },
  { type: 'Alfalfa', color: '#ffa5e2', value: CropType.ALFALFA },
  { type: 'Other Hay/Non Alfalfa', color: '#a5f28c', value: CropType.OTHER_HAY_NON_ALFALFA },
  { type: 'Camelina', color: '#00af49', value: CropType.CAMELINA },
  { type: 'Buckwheat', color: '#d69ebc', value: CropType.BUCKWHEAT },
  { type: 'Sugarbeets', color: '#a800e2', value: CropType.SUGARBEETS },
  { type: 'Dry Beans', color: '#a50000', value: CropType.DRY_BEANS },
  { type: 'Potatoes', color: '#702600', value: CropType.POTATOES },
  { type: 'Other Crops', color: '#00af49', value: CropType.OTHER_CROPS },
  { type: 'Sugarcane', color: '#af7cff', value: CropType.SUGARCANE },
  { type: 'Sweet Potatoes', color: '#702600', value: CropType.SWEET_POTATOES },
  { type: 'Watermelons', color: '#ff6666', value: CropType.WATERMELONS },
  { type: 'Onions', color: '#ffcc66', value: CropType.ONIONS },
  { type: 'Cucumbers', color: '#ff6666', value: CropType.CUCUMBERS },
  { type: 'Chick Peas', color: '#00af49', value: CropType.CHICK_PEAS },
  { type: 'Lentils', color: '#00ddaf', value: CropType.LENTILS },
  { type: 'Peas', color: '#54ff00', value: CropType.PEAS },
  { type: 'Tomatoes', color: '#f2a377', value: CropType.TOMATOES },
  { type: 'Caneberries', color: '#ff6666', value: CropType.CANEBERRIES },
  { type: 'Hops', color: '#00af49', value: CropType.HOPS },
  { type: 'Herbs', color: '#7cd3ff', value: CropType.HERBS },
  { type: 'Clover/Wildflowers', color: '#e8bfff', value: CropType.CLOVER_WILDFLOWERS },
  { type: 'Sod/Grass Seed', color: '#afffdd', value: CropType.SOD_GRASS_SEED },
  { type: 'Switchgrass', color: '#00af49', value: CropType.SWITCHGRASS },
  { type: 'Fallow/Idle Cropland', color: '#bfbf77', value: CropType.FALLOW_IDLE_CROPLAND },
  { type: 'Forest', color: '#93cc93', value: CropType.FOREST },
  { type: 'Shrubland', color: '#c6d69e', value: CropType.SHRUBLAND },
  { type: 'Barren', color: '#ccbfa3', value: CropType.BARREN },
  { type: 'Cherries', color: '#ff00ff', value: CropType.CHERRIES },
  { type: 'Peaches', color: '#ff8eaa', value: CropType.PEACHES },
  { type: 'Apples', color: '#ba004f', value: CropType.APPLES },
  { type: 'Grapes', color: '#704489', value: CropType.GRAPES },
  { type: 'Christmas Trees', color: '#007777', value: CropType.CHRISTMAS_TREES },
  { type: 'Other Tree Crops', color: '#af9970', value: CropType.OTHER_TREE_CROPS },
  { type: 'Citrus', color: '#ffff7c', value: CropType.CITRUS },
  { type: 'Pecans', color: '#b5705b', value: CropType.PECANS },
  { type: 'Almonds', color: '#00a582', value: CropType.ALMONDS },
  { type: 'Walnuts', color: '#e8d6af', value: CropType.WALNUTS },
  { type: 'Pears', color: '#af9970', value: CropType.PEARS },
  { type: 'Clouds/No Data', color: '#f2f2f2', value: CropType.CLOUDS_NO_DATA },
  { type: 'Developed', color: '#999999', value: CropType.DEVELOPED },
  { type: 'Water', color: '#4970a3', value: CropType.WATER },
  { type: 'Wetlands', color: '#7cafaf', value: CropType.WETLANDS },
  { type: 'Nonag/Undefined', color: '#e8ffbf', value: CropType.NONAG_UNDEFINED },
  { type: 'Aquaculture', color: '#00ffff', value: CropType.AQUACULTURE },
  { type: 'Open Water', color: '#4970a3', value: CropType.OPEN_WATER },
  { type: 'Perennial Ice/Snow', color: '#d3e2f9', value: CropType.PERENNIAL_ICE_SNOW },
  { type: 'Developed/Open Space', color: '#999999', value: CropType.DEVELOPED_OPEN_SPACE },
  { type: 'Developed/Low Intensity', color: '#999999', value: CropType.DEVELOPED_LOW_INTENSITY },
  { type: 'Developed/Med Intensity', color: '#999999', value: CropType.DEVELOPED_MED_INTENSITY },
  { type: 'Developed/High Intensity', color: '#999999', value: CropType.DEVELOPED_HIGH_INTENSITY },
  { type: 'Barren', color: '#ccbfa3', value: CropType.BARREN },
  { type: 'Deciduous Forest', color: '#93cc93', value: CropType.DECIDUOUS_FOREST },
  { type: 'Evergreen Forest', color: '#93cc93', value: CropType.EVERGREEN_FOREST },
  { type: 'Mixed Forest', color: '#93cc93', value: CropType.MIXED_FOREST },
  { type: 'Shrubland', color: '#c6d69e', value: CropType.SHRUBLAND },
  { type: 'Grassland/Pasture', color: '#e8ffbf', value: CropType.GRASSLAND_PASTURE },
  { type: 'Woody Wetlands', color: '#7cafaf', value: CropType.WOODY_WETLANDS },
  { type: 'Herbaceous Wetlands', color: '#7cafaf', value: CropType.HERBACEOUS_WETLANDS },
  { type: 'Pistachios', color: '#00ff8c', value: CropType.PISTACHIOS },
  { type: 'Triticale', color: '#d69ebc', value: CropType.TRITICALE },
  { type: 'Carrots', color: '#ff6666', value: CropType.CARROTS },
  { type: 'Asparagus', color: '#ff6666', value: CropType.ASPARAGUS },
  { type: 'Garlic', color: '#ff6666', value: CropType.GARLIC },
  { type: 'Cantaloupes', color: '#ff6666', value: CropType.CANTALOUPES },
  { type: 'Prunes', color: '#ff8eaa', value: CropType.PRUNES },
  { type: 'Olives', color: '#334933', value: CropType.OLIVES },
  { type: 'Oranges', color: '#e27026', value: CropType.ORANGES },
  { type: 'Honeydew Melons', color: '#ff6666', value: CropType.HONEYDEW_MELONS },
  { type: 'Broccoli', color: '#ff6666', value: CropType.BROCCOLI },
  { type: 'Peppers', color: '#ff6666', value: CropType.PEPPERS },
  { type: 'Pomegranates', color: '#af9970', value: CropType.POMEGRANATES },
  { type: 'Nectarines', color: '#ff8eaa', value: CropType.NECTARINES },
  { type: 'Greens', color: '#ff6666', value: CropType.GREENS },
  { type: 'Plums', color: '#ff8eaa', value: CropType.PLUMS },
  { type: 'Strawberries', color: '#ff6666', value: CropType.STRAWBERRIES },
  { type: 'Squash', color: '#ff6666', value: CropType.SQUASH },
  { type: 'Apricots', color: '#ff8eaa', value: CropType.APRICOTS },
  { type: 'Vetch', color: '#00af49', value: CropType.VETCH },
  { type: 'Dbl Crop WinWht/Corn', color: '#ffd300', value: CropType.DBL_CROP_WINWHT_CORN },
  { type: 'Dbl Crop Oats/Corn', color: '#ffd300', value: CropType.DBL_CROP_OATS_CORN },
  { type: 'Lettuce', color: '#ff6666', value: CropType.LETTUCE },
  { type: 'Pumpkins', color: '#ff6666', value: CropType.PUMPKINS },
  {
    type: 'Dbl Crop Lettuce/Durum Wht',
    color: '#896054',
    value: CropType.DBL_CROP_LETTUCE_DURUM_WHT
  },
  {
    type: 'Dbl Crop Lettuce/Cantaloupe',
    color: '#ff6666',
    value: CropType.DBL_CROP_LETTUCE_CANTALOUPE
  },
  { type: 'Dbl Crop Lettuce/Cotton', color: '#ff2626', value: CropType.DBL_CROP_LETTUCE_COTTON },
  { type: 'Dbl Crop Lettuce/Barley', color: '#e2007c', value: CropType.DBL_CROP_LETTUCE_BARLEY },
  {
    type: 'Dbl Crop Durum Wht/Sorghum',
    color: '#ff9e0a',
    value: CropType.DBL_CROP_DURUM_WHT_SORGHUM
  },
  { type: 'Dbl Crop Barley/Sorghum', color: '#ff9e0a', value: CropType.DBL_CROP_BARLEY_SORGHUM },
  { type: 'Dbl Crop WinWht/Sorghum', color: '#a57000', value: CropType.DBL_CROP_WINWHT_SORGHUM },
  { type: 'Dbl Crop Barley/Corn', color: '#ffd300', value: CropType.DBL_CROP_BARLEY_CORN },
  { type: 'Dbl Crop WinWht/Cotton', color: '#a57000', value: CropType.DBL_CROP_WINWHT_COTTON },
  { type: 'Dbl Crop Soybeans/Cotton', color: '#267000', value: CropType.DBL_CROP_SOYBEANS_COTTON },
  { type: 'Dbl Crop Soybeans/Oats', color: '#267000', value: CropType.DBL_CROP_SOYBEANS_OATS },
  { type: 'Dbl Crop Corn/Soybeans', color: '#ffd300', value: CropType.DBL_CROP_CORN_SOYBEANS },
  { type: 'Blueberries', color: '#000099', value: CropType.BLUEBERRIES },
  { type: 'Cabbage', color: '#ff6666', value: CropType.CABBAGE },
  { type: 'Cauliflower', color: '#ff6666', value: CropType.CAULIFLOWER },
  { type: 'Celery', color: '#ff6666', value: CropType.CELERY },
  { type: 'Radishes', color: '#ff6666', value: CropType.RADISHES },
  { type: 'Turnips', color: '#ff6666', value: CropType.TURNIPS },
  { type: 'Eggplants', color: '#ff6666', value: CropType.EGGPLANTS },
  { type: 'Gourds', color: '#ff6666', value: CropType.GOURDS },
  { type: 'Cranberries', color: '#ff6666', value: CropType.CRANBERRIES },
  { type: 'Dbl Crop Barley/Soybeans', color: '#267000', value: CropType.DBL_CROP_BARLEY_SOYBEANS },
  { type: 'CLOVER', color: '#e8bfff', value: CropType.CLOVER },
  { type: 'COVER CROP', color: '#ff6666', value: CropType.COVER_CROP },
  { type: 'EURO RYE', color: '#aa007c', value: CropType.EURO_RYE },
  { type: 'FABA BEANS', color: '#54ff00', value: CropType.FABA_BEANS },
  { type: 'FLOODING', color: '#4970a3', value: CropType.FLOODING },
  { type: 'GREEN SWISS CHARD', color: '#00af49', value: CropType.GREEN_SWISS_CHARD },
  { type: 'HARD RED WINTER WHEAT', color: '#a57000', value: CropType.HARD_RED_WINTER_WHEAT },
  { type: 'LATE CORN', color: '#ffd300', value: CropType.LATE_CORN },
  { type: 'LATE SOYBEAN', color: '#267000', value: CropType.LATE_SOYBEAN },
  { type: 'MEADOW FESCUE', color: '#a5f28c', value: CropType.MEADOW_FESCUE },
  { type: 'NONE', color: '#e8ffbf', value: CropType.NONE },
  { type: 'OTHER GRAINS', color: '#d69ebc', value: CropType.OTHER_GRAINS },
  { type: 'QUINOA AND SORGHUM', color: '#ff9e0a', value: CropType.QUINOA_AND_SORGHUM },
  { type: 'RASPBERRY', color: '#ff6666', value: CropType.RASPBERRY },
  { type: 'RED BEET', color: '#a800e2', value: CropType.RED_BEET },
  { type: 'RED SWISS CHARD', color: '#00af49', value: CropType.RED_SWISS_CHARD },
  { type: 'UNKNOWN CROPTYPE', color: '#f2f2f2', value: CropType.UNKNOWN_CROPTYPE },
  { type: 'WET CORN', color: '#ffd300', value: CropType.WET_CORN },
  { type: 'WHEAT', color: '#BF870D', value: CropType.WHEAT }
];

export enum TillageType {
  TILLIAGE_TYPE_UNKNOWN = 0,
  NOT_TILLAGE = 1,
  CONVENTIONAL_TILLAGE = 2,
  REDUCED_TILLAGE = 3,
  TILLAGE_NOT_AGRICULTURE_LAND = 4,
  NO_CROP = 5,
  PRIMARY_TILLAGE = 6,
  SECONDARY_TILLAGE = 7,
  DEEP_TILLAGE = 8,
  RIPPING_TILLAGE = 9,
  DISK_TILLAGE = 10,
  BASKET_TILLAGE = 11,
  SHANK_TILLAGE = 12,
  DISK_ANGLE_TILLAGE = 13,
  ROTARY_HOE_TILLAGE = 14,
  ROW_CROP_CULTIVATING_TILLAGE = 15,
  RIPPER_TILLAGE = 16,
  COULTER_TILLAGE = 17
}

export const TILLAGE_COLORS = [
  { type: 'Tilliage type unknown', color: '#F9E3DE' },
  { type: 'Not tillage', color: '#A57C6E' },
  { type: 'Conventional tillage', color: '#FFF7C1' },
  { type: 'Reduced tillage', color: '#D47A5B' },
  { type: 'Tillage not agriculture land', color: '#E8E6E6' },
  { type: 'No crop', color: '#C4C4C4' },
  { type: 'PRIMARY TILLAGE', color: '#D8EEDE' }
];

export enum CoverCropType {
  COVER_CROP_UNKNOWN = 0,
  WITH_COVER_CROP = 1,
  WITH_WINTER_COVER_CROP = 4,
  WITH_SPRING_COVER_CROP = 5,
  NOT_COVER_CROP = 2,
  COVER_CROP_NOT_AGRICULTURE_LAND = 3
}

export const COVER_CROP_COLORS = [
  { type: 'Cover crop unknown', color: '#F9E3DE' },
  { type: 'With cover crop', color: '#125B2E' },
  { type: 'With winter cover crop', color: '#0B6E8D' },
  { type: 'With spring cover crop', color: '#8D0B0B' },
  { type: 'Not cover crop', color: '#BEA79E' },
  { type: 'Cover crop not agriculture land', color: '#E8E6E6' }
];
